type: default # 选择模板

#default
name: 符少磊
objective: Android开发实习生 #求职意向

sex: 男
birthday: 1999.05
university: 河北师范大学 # 大学
profession: 软件工程-Android方向 # 专业
status: 本科
graduation: 2021
avator: https://cdn.jsdelivr.net/gh/fushaolei/img/20200606214411.png

# contact
blog: sorryfu.top
github: github.com/FuShaoLei
email: 1563250958@qq.com
phone: 18389621811

#project 项目
project:
  亲逢APP:
    - 2019.11-2019.12
    - github
    - https://github.com/zhangyiweizyw/searchForLovedOnes
    - 亲逢APP是由我和我的小组成员写的实训项目，我在里边主要负责寻人大厅模块 ，通过使用okhttp来与服务端进行交互，使用glide来获取服务端的图片，实现id和名字查询的服务端和客户端,，通过这次项目我收获了很多经验，对软件开发也有了一定的认知
  诗韵APP:
    - 2020.03-2020.06
    - github
    - https://github.com/zhangyiweizyw/PoetryRhyme
    - 诗韵APP是由我和我的小组成员写的实训项目，我主要负责首页，还有我的 的UI部分，以及游戏（包括单人游戏/双人游戏）的前后端，其中双人游戏的逻辑是：两台客户端通过socket连接到服务器，由服务器进行一一匹配，然后由服务器出题，双方进行答题，双方答题的数据通过输出流传到对方的客户端，同步ui。这是我做这个项目最大的收获



#skill
skill:
  - 熟练使用eclipse，Android studio等软件
  - 了解SpringBoot SpringMVC MyBatis等框架的
  - 熟悉Java语言的使用
  - 熟练使用Git进行版本控制和代码托管、Markdown进行文档编写